os: linux
dist: xenial
language: python
install:
  - git init
  - git remote add origin https://safinsingh:${GH_TOKEN}@github.com/safinsingh/ParadoxSE.git > /dev/null 2>&1
  - git pull
  - pip install -r requirements.txt
  - sudo apt-get install --reinstall python3-apt
  - pip install pdoc3
  - rm -rf docs
  - pdoc --html paradox -o docs
  - find docs -type f -print -exec mv {} . \;
  - rm -rf docs/paradox
  - git config --global user.email "safin.singh@gmail.com"
  - git config --global user.name "Safin Singh"
  - git add docs
  - git commit -m "auto regen docs (travis)"
  - git push origin master --quiet

env:
  global:
    secure: FpyerkmVA/OYJDPzc0HmL2cY3929+/rLEx1qHIT6rg5cR8oM6+LqZB5BeV0xFSPN7tRk0l+3reBWPWHcXNPKYALgixSaU2D5LXAnvxo13zY080iN5IyD0s5blf5o0TJRyAMnW1EPpqzBcwZ/V7tzAeENqY2mCty0/JJ2Q4wR9zvK/V+yPHykcua7KjSKsano/MStXS6KmdurA98p88WwcGE9kiytxFT2k49bV9NleHeLJnUfp78I0eWtMG9j+L9kr04mGxmFMt2GUjZrS7PKpJ492SpVZTUyAtiM+kuZP3a07/4TyBhgfO6IhEgr6xp0dIt/yTF4hpUrbtXH0PvmKKcUitzDXoVFX/5+tkofrQWfxcuEZGcZei6iRmny3nwOd/ojNAoqhHuXGA9mbj+1ia9PlENeOzYeFrzYFHM1PuEeMBFrEX1TAnuwbODLVxgNrtgkJolUE4rhPGTp+ndugtgOWNV42Zf+L+DzEyoI3fJRhE3ejGNhbZgwwOBQyz3jWfo7u3/os1A9PiOgpt0SCeNzRunZgYUOJ8X7W223JNxwN48eSRJtH70iFDao5cnLxD30hcf9FihC348PVlWm1ihKEIa5XVoRWSVNFK0WIzjKRJsQWYYCvNZQn2U6Tgi5uBv73Zs8lN3ddtwChaUz2UVz4yGqKbRyEtuneRI07jM=
